name: Makefile CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Make
        run: make

      - name: Deploy font files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          username: ${{ secrets.CDNET_BLOB01_USER }}
          server: ${{ secretts.CDNET_BLOB01 }}
          ssh_private_key: ${{ secrets.CDNET_BLOB01_KEY }}
          sftp_only: true
          local_path: "./out/"
          remote_path: "/1374ad54-0d58-42c3-aaa9-ef523652e19e/72294871-5af6-49a2-a359-bd2b81973847/"
